### ISSUE TITLE
[FEATURE] Support multiple condition check in task condition check

### ISSUE THREAD

**Issue by zhiyaoPCCW** [mycloudnexus/kraken#443]
a/c: 

- Support multiple condition check which maybe joined by 'or' or 'and'
- Configure operator list in backend
- condition check could work correctly with multiple condition in workflow

**Comment by zhiyaoPCCW** [comment]
- Changes on template

```
      conditionCheck:
        join: OR
        conditionItems:
          - operator: IN
            value: DELETED
            expression: status_checking_task.stateList
          - operator: GREATER_THAN
            value: 1
            expression: status_checking_task.count
```
join: indicate how the multiple conditions join together, tow join operator supported: 

```
  OR("||"),
  AND("&&");
```
conditionItems.operator: several operator supported 
```
      EQUAL("=="),
      NOT_EQUAL("!="),
      GREATER_THAN(">"),
      GREATER_THAN_OR_EQUAL_TO(">="),
      LESS_THAN_OR_EQUAL_TO("<="),
      IN("in")
```

- Implement
Add new build-in task to support multiple condition check, because conductor can not support complex expression very well.
