### ISSUE TITLE
new product type support in app level and component level should be configurable

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#595]
a/c:

- what kind of product type are support at application level is configurable
- under each component, what kind of product type are supported is configurable

**Comment by zhiyaoPCCW** [comment]
- For a/c 1: 
  Add productType configuration  : 
```
  product-types:
    - UNI
    - ACCESS_E_LINE
    - INTERNET_ACCESS
    - SHARE
```
- For a/c 2: 
  Add supported-product-types configuration: 

```
  supported-product-types:
    address:
      - SHARE
    order:
      - UNI
      - ACCESS_E_LINE
    quote:
      - UNI
      - ACCESS_E_LINE
    poq:
      - UNI
      - ACCESS_E_LINE
    inventory:
      - UNI
      - ACCESS_E_LINE
```
- Changes on template: 
  add `supportedConfig` to evaluate property from application.yaml
```
  supportedProductTypesAndActions:
    - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
      method: post
      actionTypes:
        - add
        - modify
        - delete
      supportedConfig: $.order
    - path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
      method: get
      actionTypes:
        - add
        - modify
        - delete
      supportedConfig: $.order
```
